services:
  app:
    build: .
    container_name: notes-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notesdb
    depends_on:
      - mongo
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/notes"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6.0.5
    container_name: notes-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
